# Generated by Django 3.2.15 on 2022-09-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathermodel',
            options={'verbose_name': 'Weather Type', 'verbose_name_plural': 'Weather Types'},
        ),
    ]
