# Generated by Django 3.2.15 on 2022-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0002_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
